### ISSUE TITLE
Extracion and/or building dump not working as expected

### ISSUE THREAD

**Issue by RustyRaindeer** [andy-man/ps5-wee-tools#4]
PS5 wee tools 0.1.5
platform: both windows and Linux

If you run "extract sFlash's partitions" and try to "Build dump from extracted files" back again, it does not produce a valid file. 
If you try to select the generated file (to analyze it), wee tools complains about "Unknown file type".

I run a manual diff with the original file, agains the produced sflash0.bin, they seem to be different starting from address 120000h.
The data in sflash0.bin (that was re-created from the extracted files) contains the data from "unknown" partition at that point, but does not correspond to the original NOR dump file. Maybe the error is produced already when extracting partitions.

![image](https://github.com/andy-man/ps5-wee-tools/assets/6859581/66c3e09e-61d9-45c9-813e-2a74b2fb32ea)

**Comment by andy-man** [comment]
thanks for correction (merged)
